# MongoDB conf
spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: SchemaRepo
      repositories:
        type: auto
# spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Elixir Validator
elixirValidator:
  hostUrl: http://localhost:3000/validate

# BioSample AAP Conf
aap:
  url: https://explore.api.aai.ebi.ac.uk
  schemaAuthority: ROLE_self.json-schema-store
jwt:
  certificate: https://explore.api.aai.ebi.ac.uk/meta/public.der
#aap-client:
#  cors:
#    enabled: true