# MongoDB conf
spring:
  data:
    mongodb:
      port: 27030
      host: localhost
      database: SchemaRepo
      repositories:
        type: auto
# Elixir Validator
elixirValidator:
  hostUrl: http://localhost:3000/validate

# BioSample AAP Conf
aap:
  url: https://explore.api.aai.ebi.ac.uk
jwt:
  certificate: https://explore.api.aai.ebi.ac.uk/meta/public.der
