variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_TAG
  DOCKER_PULL_SECRET: docker-registry-secret
  DOCKER_AUTH_CONFIG: $DOCKER_CONFIG_JSON

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - publish

build:
  stage: build
  image: maven:latest
  script:
    - mvn package -DskipTests -Pprod
  artifacts:
    paths:
      - target/json-schema-store-0.0.1-SNAPSHOT.jar

build_image_and_publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - echo $DOCKER_IMAGE_NAME
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  after_script:
    - docker logout ${CI_REGISTRY}

