image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-DskipTests"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/json-schema-store-0.0.1-SNAPSHOT.jar

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test
#
deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$NOAH_LOGIN_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ebi-cli >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -v -o StrictHostKeyChecking=no isuru@ebi-cli rm -rf /nfs/spot/data/test/biosamples/json-schema-store
    - scp -r -v -o StrictHostKeyChecking=no . isuru@ebi-cli:/nfs/spot/data/test/biosamples/json-schema-store
    - ssh ebi-cli become spotbot "ssh scooby 'scp ebi-cli:target/storeroom/storeroom-0.0.1-SNAPSHOT.jar /mnt/data/biosamples/sw/wwwdev/storeroom.jar'"
  only:
    - master