image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-DskipTests"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test
#
#deploy:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
#  only:
#    - master