image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-DskipTests"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
#  - test
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/json-schema-store-0.0.1-SNAPSHOT.jar

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test
#
deploy:
  image: ubuntu
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$BSD_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ebi-cli >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m2-3d "rm -rf ~/deployments/sw/www/json-schema-store"
    - scp -r -v -o StrictHostKeyChecking=no ./target tc_spo01@wp-p1m2-3d:~/deployments/sw/www/json-schema-store
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m2-3d "export JAVA_HOME=~/servers/jdk-11"
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m2-3d "export PATH=~/servers/jdk-11/bin:$PATH"
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m2-3d "cp ~/config/application.yml  ~/deployments/sw/www/json-schema-store/"
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m2-3d "nohup java -jar ~/deployments/sw/www/json-schema-store/json-schema-store-0.0.1-SNAPSHOT.jar &"
#  only:
#    - master