variables:
  MAVEN_CLI_OPTS: "-DskipTests"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_TAG
  DOCKER_PULL_SECRET: docker-registry-secret

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
#  - test
  - publish
  - deploy

build:
  image: maven:3.8.3-openjdk-17
  stage: build
  variables:
    MONGO_URL: $DEV_MONGO_URL
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/json-schema-store-0.0.2.jar

build_docker_image:
  image: docker:latest
  services:
    - docker:dind
  stage: publish
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - echo $DOCKER_IMAGE_NAME
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  after_script:
    - docker logout ${CI_REGISTRY}

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test
#
deploy_dev:
  variables:
    NAMESPACE: biosamples-dev
    HOST: wwwint.ebi.ac.uk
    MONGO_URL: $DEV_MONGO_URL
    VALIDATOR_URL: https://wwwdev.ebi.ac.uk/ait/biovalidator/validate
  environment:
    name: dev
    url: https://wwwint.ebi.ac.uk/biosamples/schema-store
  extends: .kube_deploy_script

deploy_test:
  variables:
    NAMESPACE: biosamples-test
    HOST: wwwdev.ebi.ac.uk
    MONGO_URL: $TEST_MONGO_URL
    VALIDATOR_URL: https://wwwdev.ebi.ac.uk/ait/biovalidator/validate
  environment:
    name: test
    url: https://wwwdev.ebi.ac.uk/biosamples/schema-store
  when: manual
  extends: .kube_deploy_script

deploy_prod:
  variables:
    NAMESPACE: biosamples-prod
    HOST: www.ebi.ac.uk
    MONGO_URL: $PROD_MONGO_URL
    VALIDATOR_URL: https://wwwdev.ebi.ac.uk/ait/biovalidator/validate
  environment:
    name: prod
    url: https://www.ebi.ac.uk/biosamples/schema-store
  when: manual
  extends: .kube_deploy_script

.kube_deploy_script:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl create namespace $NAMESPACE || true
    - kubectl config set-context --current --namespace=${NAMESPACE}
    - kubectl delete secret $DOCKER_PULL_SECRET || true
    - kubectl create secret docker-registry $DOCKER_PULL_SECRET --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD
    - envsubst < k8s/deployment.yaml > kubernetes.yaml
    - kubectl apply -f kubernetes.yaml
    - kubectl apply -f k8s/service.yaml
    - kubectl rollout restart deployments json-schema-store

