image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-DskipTests"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/storeroom/storeroom-0.0.1-SNAPSHOT.jar

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test
#
deploy:
  stage: deploy
  script:
    - ssh ebi-cli become spotbot "ssh scooby 'scp ebi-cli:target/storeroom/storeroom-0.0.1-SNAPSHOT.jar /mnt/data/biosamples/sw/wwwdev/agents-solr.jar'"
  only:
    - master