variables:
  MAVEN_CLI_OPTS: "-DskipTests"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_TAG
  DOCKER_PULL_SECRET: docker-registry-secret

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
#  - test
  - publish
  - deploy

build:
  image: maven:3.8-openjdk-11
  stage: build
  variables:
    MONGO_URL: $MONGO_URI
  script:
    - mvn $MAVEN_CLI_OPTS clean package -Pdocker
  artifacts:
    paths:
      - target/json-schema-store-0.0.2.jar

build_docker_image:
  image: docker:latest
  services:
    - docker:dind
  stage: publish
  variables:
    MONGO_URL: $MONGO_URI
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - echo $DOCKER_IMAGE_NAME
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  after_script:
    - docker logout ${CI_REGISTRY}

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test
#
deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.11.0
  script:
    - kubectl create namespace $KUBECTL_NAMESPACE || true
    - kubectl config set-context --current --namespace=${KUBECTL_NAMESPACE}
    - kubectl delete secret $DOCKER_PULL_SECRET || true
    - kubectl create secret docker-registry $DOCKER_PULL_SECRET --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD
    - envsubst < deployment.yaml > kubernetes.yaml
    - kubectl apply -f kubernetes.yaml
    - kubectl rollout restart deployments json-schema-store
  when: manual

