image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-DskipTests"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
#  - test
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package -Pprod
  artifacts:
    paths:
      - target/json-schema-store-0.0.1-SNAPSHOT.jar

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test
#
deploy:
  image: ubuntu
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$BSD_PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ebi-cli >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m2-3d "rm -rf ~/deployments/sw/www/json-schema-store/*"
    - scp -r -v -o StrictHostKeyChecking=no ./target/json-schema-store-*.jar tc_spo01@wp-p1m2-3d:~/deployments/sw/www/json-schema-store/json-schema-store.jar
    - ssh -v -o StrictHostKeyChecking=no tc_spo01@wp-p1m2-3d "~/config/start.sh"
#  only:
#    - master

deploy-dev-json-schema-store-k8:
  image: dtzar/helm-kubectl
  stage: deploy
  script:
    - sed -i s#%DOCKER_IMAGE%#$CI_REGISTRY_IMAGE\:$CI_COMMIT_SHA#g Kubernetes-dev-deployment.yaml
    - kubectl delete secret gitlab --namespace=bsd-dev
    - kubectl create secret docker-registry gitlab --docker-server=$CI_REGISTRY --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASSWORD --docker-email=$DOCKER_EMAIL --namespace=bsd-dev
    - kubectl apply -f Kubernetes-dev-deployment.yaml --namespace=bsd-dev
  when: manual
