variables:
  MAVEN_CLI_OPTS: "-DskipTests"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$DOCKER_TAG
  DOCKER_PULL_SECRET: docker-registry-secret
  K8S_NAMESPACE_PREFIX: biosamples
  APP_NAME: $CI_PROJECT_NAME

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
#  - test
  - publish
  - deploy

build:
  image: maven:3.8.3-openjdk-17
  stage: build
  variables:
    MONGO_URL: $DEV_MONGO_URL
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/json-schema-store-0.0.2.jar

build_docker_image:
  image: docker:latest
  services:
    - docker:dind
  stage: publish
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - echo $DOCKER_IMAGE_NAME
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  after_script:
    - docker logout ${CI_REGISTRY}

#test:
#  stage: test
#  script:
#    - mvn $MAVEN_CLI_OPTS test
#

deploy_dev:
  variables:
    ENVIRONMENT_NAME: dev
    HOST: wwwint.ebi.ac.uk
    VALIDATOR_URL: https://wwwint.ebi.ac.uk/biosamples/biovalidator/validate
  environment:
    name: dev
    url: https://wwwint.ebi.ac.uk/biosamples/schema-store/api/v2
  only:
    - dev
  extends: .kube_deploy_script

# TODO: add test and prod after validation of dev

.kube_deploy_script:
  stage: deploy
  image: dtzar/helm-kubectl
  variables:
    K8S_NAMESPACE: ${K8S_NAMESPACE_PREFIX}-${ENVIRONMENT_NAME}
  script:
    - kubectl create namespace ${K8S_NAMESPACE} || true
    - kubectl config set-context --current --namespace=${K8S_NAMESPACE}
    - kubectl delete secret $DOCKER_PULL_SECRET || true
    - kubectl create secret docker-registry $DOCKER_PULL_SECRET --docker-server=$CI_REGISTRY --docker-username=$CI_DEPLOY_USER --docker-password=$CI_DEPLOY_PASSWORD
    - mkdir k8s.$$
    - envsubst < k8s/configmap.yaml > k8s.$$/configmap.yaml
    - envsubst < k8s/deployment.yaml > k8s.$$/deployment.yaml
    - envsubst < k8s/service.yaml > k8s.$$/service.yaml
    - envsubst < k8s/ingress.yaml > k8s.$$/ingress.yaml
    - kubectl apply -f k8s.$$/
    - kubectl rollout restart deployments json-schema-store

