version: '3'
services:
  mongodb:
    image: mongo:4.2.6
    container_name: "SchemaRepo"
    command: mongod --port 27030
    ports:
    - 27030:27030
  validator:
    image: ebispot/elixir-jsonsschema-validator:1.3.0
    container_name: "validator"
    command: npm start
    ports:
      - 3000:3020
  app:
    build: .
    image: biosamples/json-schema-store:latest
    ports:
    - 8080:8080
    links:
      - mongodb
      - validator
