version: '3'
services:
  mongodb:
    image: mongo:4.2.6
    container_name: "SchemaRepo"
    ports:
      - 27017:27017
  validator:
    image: ebispot/elixir-jsonsschema-validator:1.3.0
    container_name: "validator"
    command: npm start
    ports:
      - 3000:3020
  app:
    build: .
    image: biosamples/json-schema-store:latest
    ports:
      - 8080:8080
    links:
      - mongodb
      - validator
#networks:
#  default:
#    ipam:
#      config:
#        - subnet: 172.30.0.0/16