version: '3'
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
    - 27017:27017
    command: --smallfiles
  app:
    build: .
    image: hashan/jsonschema:latest
    ports:
    - 8080:8080
    links:
      - mongodb
