spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://localhost/schemastore
    rest:
      basePath: /api/v2

management:
  endpoints:
    web:
      exposure:
        include: "*"
auth:
  api:
    url: https://wwwdev.ebi.ac.uk/ena/submit/webin/auth
logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          rest:
            webmvc:
              json: INFO
        web: DEBUG
    uk:
      ac:
        ebi:
          biosamples:
            jsonschemastore: INFO
