# MongoDB conf
spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: schemastore
      repositories:
        type: auto
# Elixir Validator
schemastore:
  validator:
    url: http://localhost:3020/validate