spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    rest:
      basePath: /api/v2
server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: "*"
auth:
  api:
    url: https://www.ebi.ac.uk/ena/submit/webin/auth
ena:
  checklists:
    url: https://www.ebi.ac.uk/ena/submit/report/checklists
  checklist:
    groups:
      url: https://www.ebi.ac.uk/ena/submit/report/checklist-groups

logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          rest:
            webmvc:
              json: INFO
        web: DEBUG
    uk:
      ac:
        ebi:
          biosamples:
            jsonschemastore: INFO
