# MongoDB conf
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/schemastore
      database: schemastore
      repositories:
        type: auto
      auto-index-creation: true
    rest:
      basePath: /api/v2
# spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Elixir Validator
schemastore:
  validator:
    url: http://localhost:3020/validate

logging:
  level:
    org:
      springframework:
        security: DEBUG
