# MongoDB conf
spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
server:
  port: 8085
  servlet:
    context-path: /schema-store
# spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Elixir Validator
schemastore:
  validator:
    url: https://wwwdev.ebi.ac.uk/ait/biovalidator/validate
