spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    rest:
      basePath: /api/v2
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          rest:
            webmvc:
              json: INFO
        web: DEBUG
    uk:
      ac:
        ebi:
          biosamples:
            jsonschemastore: INFO
