spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      springframework:
        security: INFO
    uk:
      ac:
        ebi:
          biosamples:
            jsonschemastore: INFO
