# MongoDB conf
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
# spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Elixir Validator
schemastore:
  validator:
    url: https://wwwdev.ebi.ac.uk/ait/biovalidator/validate

logging:
  level:
    org:
      springframework:
        security: DEBUG
