spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org:
      springframework:
        security: WARN
    uk:
      ac:
        ebi:
          biosamples:
            jsonschemastore: INFO


# Elixir Validator
schemastore:
  validator:
    url: http://localhost:3020/validate
