# MongoDB conf
spring:
  data:
    mongodb:
      port: 27017
      host: mongodb
      database: schemastore
      repositories:
        type: auto
server:
  port: 8085
# spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Elixir Validator
elixirValidator:
  hostUrl: http://validator:3020/validate
