apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ${NAMESPACE}
data:
  application.yaml: |
    schemastore:
      validator:
        url: ${VALIDATOR_URL}
    spring:
      data:
        mongodb:
          url: ${MONGO_URL}
        
