apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: json-schema-store
  name: json-schema-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-schema-store
  template:
    metadata:
      labels:
        app: json-schema-store
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      containers:
        - name: json-schema-store
          image: $DOCKER_IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATA_MOBGODB_URI
              value: ${MONGO_URI}
            - name: SCHEMASTORE_VALIDATOR_URL
              value: ${VALIDATOR_URL}

