apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: json-schema-store
  name: json-schema-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-schema-store
  template:
    metadata:
      labels:
        app: json-schema-store
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      containers:
        - name: json-schema-store
          image: $DOCKER_IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: json-schema-store-secret      # The name of the secret
                  key: spring.data.mongodb.uri        # The key in the secret
            - name: SCHEMASTORE_VALIDATOR_URL
              valueFrom:
                configMapKeyRef:
                  name: json-schema-store-config
                  key: schemastore.validator.url

