apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: schema-store
  name: schema-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: schema-store
  template:
    metadata:
      labels:
        app: schema-store
    spec:
      imagePullSecrets:
        - name: $DOCKER_PULL_SECRET
      containers:
        - name: schema-store
          image: $DOCKER_IMAGE_NAME
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: biovalidator-service
spec:
  type: NodePort
  selector:
    app: schema-store
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080