# MongoDB conf
spring:
  data:
    mongodb:
      port: 0
      host: localhost
      database: SchemaRepo
      repositories:
        type: auto
# Elixir Validator
elixirValidator:
  hostUrl: http://localhost:3000/validate
