# MongoDB conf
spring:
  data:
    mongodb:
      port: 27017 # for docker run 27018
      host: localhost # for docker "schema-repo"
      database: SchemaRepo
      repositories:
        type: auto
